# Generated by Django 3.2.5 on 2022-11-09 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_testflight'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestFlight',
        ),
    ]
